learn_dqn:
	poetry run python dqn_learn.py

learn_dqn_hard:
	poetry run python dqn_hard_learn.py

learn_dqn_soft:
	poetry run python dqn_soft_learn.py

learn_dqn_double:
	poetry run python dqn_double_learn.py
